### ISSUE TITLE
Add support for YARD

### ISSUE THREAD

**Issue by postmodern** [bkuhlmann/rubysmith#2]
## Overview

It would be nice if rubysmith supported adding [yard](https://yardoc.org/) to the gemspec and adding the `YARD::Rake::YardocTask` to the `Rakefile`.

### Example

in the `.gemspec`:

```ruby
  gem.add_development_dependency 'yard', '~> 0.9'
```

or in the `Gemfile`:

```ruby
gem 'yard', '~> 0.9'
```

`Rakefile`:

```ruby
require 'yard'
YARD::Rake::YardocTask.new
```

**Comment by bkuhlmann** [comment]
Thanks. Yeah, so like a `--yard` build option that would enable this for you when generating a new project? That sounds reasonable but I'd like to delve into this a bit more.

How do you use Yard in your own projects? Are any specific projects of yours that I should look at that would demonstrate this well? I don't use Yard, myself, but would like to understand how you use it more.

...but, in general, adding a flag for this seems reasonable.

**Comment by postmodern** [comment]
Take a look at any of my Ruby projects (ex: [hexdump.rb](https://github.com/postmodern/hexdump.rb)). You add the dependency, add the rake task, then annotate methods with the YARD tags similar to JavaDoc. Additional options can be passed to YARD via the `.yardopts` file, and it will also respect the `.document` file which lists globs/paths of files to include in the documentation. Occasionally, I run `rake yard` or `rake doc` (I alias `doc` to  `yard`) to ensure there's no typos in the documentation. The creator of YARD also setup [rubydoc.info](https://rubydoc.info/) which generates the HTML documentation for gems on-demand.
